ShopAgent/config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'

  get 'inquiry/confirm'

  get 'inquiry/thanks'

  get 'use_sample/top'

  get 'home/top'

  get 'faq/top'

  resources :orders

  resources :posts

  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  root to: 'home#top', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ShopAgent/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ShopAgent/app/models/inquiry.rb
class Inquiry
	include ActiveModel::Model

	attr_accessor :name, :email, :message

	validates :name, :presence => {:message => '名前を入力してください'}
	validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

ShopAgent/app/models/order.rb
class Order < ApplicationRecord
	PAYMENT_TYPES = ["ネットバンク振込","クレジットカード決済","コンビニ振込"]
end

ShopAgent/app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
end

ShopAgent/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ShopAgent/app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def top
  end
end

ShopAgent/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@posts = Post.all.order(created_at: 'desc').limit(3)
  end
end

ShopAgent/app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
  	@inquiry = Inquiry.new
  	render :action => 'index'
  end

  def confirm
  	@inquiry = Inquiry.new(inquiry_params)

  	if @inquiry.valid?
  		render :action => 'confirm'
  	else
  		render :action => 'index'
  	end
  end

  def thanks
  	@inquiry = Inquiry.new(inquiry_params)
  	InquiryMailer.received_email(@inquiry).deliver

  	render :action => 'thanks'

  end

  private
  def inquiry_params
  	params.require(:inquiry).permit(:name, :email, :message)
  end
end

ShopAgent/app/controllers/my_sns_controller.rb
class MySnsController < ApplicationController
	def index
		#参考
		#https://qiita.com/Kenya/items/1cfb108fe3292e5d20bb
		#https://qiita.com/sleeping_tiger/items/dd97839384c62616863f
	end
end

ShopAgent/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :tellNo, :email, :productName, :productDescription, :image_url, :shopAddress, :pay_type)
    end
end

ShopAgent/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.order(created_at: 'desc')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])

	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

ShopAgent/app/controllers/use_sample_controller.rb
class UseSampleController < ApplicationController
  def top
  end
end

ShopAgent/app/helpers/application_helper.rb
module ApplicationHelper
end

ShopAgent/app/helpers/faq_helper.rb
module FaqHelper
end

ShopAgent/app/helpers/home_helper.rb
module HomeHelper
end

ShopAgent/app/helpers/inquiry_helper.rb
module InquiryHelper
end

ShopAgent/app/helpers/my_sns_helper.rb
module MySnsHelper
end

ShopAgent/app/helpers/orders_helper.rb
module OrdersHelper
end

ShopAgent/app/helpers/posts_helper.rb
module PostsHelper
end

ShopAgent/app/helpers/use_sample_helper.rb
module UseSampleHelper
end

ShopAgent/app/views/faq/top.html.erb
<h1>Faq#top</h1>
<p>Find me in app/views/faq/top.html.erb</p>

ShopAgent/app/views/home/top.html.erb
<h1>Home#top</h1>
<%= link_to "ご利用サンプル", use_sample_top_path %>
<%= link_to "お問い合わせ", inquiry_index_path %>

<%= link_to 'FAQ', faq_top_path %>
<%= button_to "注文する", new_order_path, method: :get %>
<h2>最新記事</h2>
<%= render 'posts/index'%>

ShopAgent/app/views/inquiry/confirm.html.erb
<div class="page-header">
	<h1>お問い合わせ</h1>
</div>

<h2>内容のご確認</h2>

<p>問題がなければ送信ボタンを押してください。</p>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
<table class="table">
	<tr>
		<th>名前</th>
		<td>
			<%= f.hidden_field :name %>
			<%= @inquiry.name %>
		</td>
	</tr>
	<tr>
		<th>メールアドレス</th>
		<td>
			<%= f.hidden_field :email %>
			<%= @inquiry.email %>
		</td>
	</tr>
	<tr>
		<th>お問い合わせ内容</th>
		<td>
			<%= f.hidden_field :message %>
			<%= simple_format(@inquiry.message) %>
		</td>
	</tr>
</table>
<%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

ShopAgent/app/views/inquiry/index.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
	<div class="page-header">
		<h1>お問い合わせ</h1>
	</div>

	<h2>
		内容のご入力
	</h2>

	<p>お問い合わせ内容をご入力ください。</p>

	<% if @inquiry.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<strong>入力内容にエラーがあります</strong>
			<ul>
				<% @inquiry.errors.each do |attr, msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<table class="table">
		<tr>
			<th>名前<span class="text-danger">(必須)</span></th>
			<td><%= f.text_field :name %></td>

		</tr>
		<tr>
			<th>メールアドレス<span class="text-danger">(必須)</span></th>
			<td><%= f.text_field :email %></td>
		</tr>
		<tr>
			<th>お問い合わせ内容</th>
			<td><%= f.text_area :message %></td>
		</tr>
	</table>
	<%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

ShopAgent/app/views/inquiry/thanks.html.erb
<div class="page-header">
	<h1>お問い合わせ</h1>
</div>

<h2>
	お問い合わせいただきありがとうございました。
</h2>
<p>
	確認完了次第、折り返しご連絡いたします。
</p>

ShopAgent/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopAgent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<li><%= link_to 'Topページ', home_top_path %></li>
    <%= yield %>
  </body>
</html>

ShopAgent/app/views/my_sns/index.html.erb
<h2>SNS</h2>

ShopAgent/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'ご注文者様のご氏名(必須)' %>
    <%= form.text_field :name, id: :order_name %>
  </div>

  <div class="field">
    <%= form.label 'お届け先住所(必須)' %>
    <%= form.text_area :address, id: :order_address %>
  </div>

  <div class="field">
    <%= form.label 'ご注文者様のお電話番号(必須)' %>
    <%= form.text_field :tellNo, id: :order_tellNo %>
  </div>

  <div class="field">
    <%= form.label 'ご注文者様のメールアドレス' %>
    <%= form.text_field :email, id: :order_email %>
  </div>

  <div class="field">
    <%= form.label 'ご注文の商品名(必須)' %>
    <%= form.text_field :productName, id: :order_productName %>
  </div>

  <div class="field">
    <%= form.label '注文品のご説明' %>
    <%= form.text_area :productDescription, id: :order_productDescription %>
  </div>

  <div class="field">
    <%= form.label '画像ファイル' %>
    <%= form.text_field :image_url, id: :order_image_url %>
  </div>

  <div class="field">
    <%= form.label '販売先のご住所' %>
    <%= form.text_area :shopAddress, id: :order_shopAddress %>
  </div>

  <div class="field">
    <%= form.label 'お支払い方法(必須)' %>
    <%= form.select :pay_type, Order::PAYMENT_TYPES,
      prompt: 'お支払い方法を選択してください' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ShopAgent/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

ShopAgent/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Tellno</th>
      <th>Email</th>
      <th>Productname</th>
      <th>Productdescription</th>
      <th>Image url</th>
      <th>Shopaddress</th>
      <th>pay_type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.tellNo %></td>
        <td><%= order.email %></td>
        <td><%= order.productName %></td>
        <td><%= order.productDescription %></td>
        <td><%= order.image_url %></td>
        <td><%= order.shopAddress %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

ShopAgent/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

ShopAgent/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Tellno:</strong>
  <%= @order.tellNo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Productname:</strong>
  <%= @order.productName %>
</p>

<p>
  <strong>Productdescription:</strong>
  <%= @order.productDescription %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @order.image_url %>
</p>

<p>
  <strong>Shopaddress:</strong>
  <%= @order.shopAddress %>
</p>

<p>
  <strong>pay_type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

ShopAgent/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@post.errors.count,
		 "error") %> prohibited this post from being saved:</h2>
		 <ul>
		 	<% @post.errors.full_messages.each do |msg| %>
		 	<li><%= msg %></li>
		 	<% end %>
		 </ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %>
		<br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

ShopAgent/app/views/posts/_index.html.erb
	<% @posts.each do |post|  %>
	<h2><%= link_to post.title, post_path(post) %></h2>
	<p class="postsPrintClass"><%= post.body %></p>
	<p><%= link_to 'Edit', edit_post_path(post) %>
	<%= link_to 'Destroy', post_path(post),
		method: :delete, data: {confirm: 'Are you sure?'} %></p>
	<% end %>

ShopAgent/app/views/posts/edit.html.erb
<h1>Editing</h1>


<%= render 'form' %>

<%= link_to '一覧へ', posts_path %>

ShopAgent/app/views/posts/index.html.erb
<h2>記事一覧</h2>

<%= render 'index' %>

<%= link_to 'New article', new_post_path %>

ShopAgent/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to '一覧へ', posts_path %>

ShopAgent/app/views/posts/show.html.erb
<h2>
	<%= @post.title %>
</h2>

<p>
	<%= simple_format(@post.body) %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %>

<%= link_to '一覧へ', posts_path %>

ShopAgent/app/views/use_sample/top.html.erb
<h1>ご利用サンプル</h1>

<li>料金例</li>
<li>その他のプラン<li>


<p>Find me in app/views/use_sample/top.html.erb</p>